# -*- coding: utf-8 -*-
"""Python Conexion Postgesql.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AJTZ54lOwqIPri7R2gnmv3Z4KEoDZDZw
"""

pip install psycopg2

import psycopg2



import psycopg2



cursor = conn.cursor()
cursor.execute("INSERT INTO consultora_pais (nombre) VALUES ('Senegal')")
conn.close()

conn = psycopg2.connect(
   database="d6dnjthjdhcjg2", 
   user='mhoadzckqtelgg', 
   password='d23acd0a4b499eb1ea118026c36297aa9e19dd60dfdee4c17d146341eebffdd2', 
   host='ec2-54-175-79-57.compute-1.amazonaws.com', 
   port= '5432'
)

cursor = conn.cursor()
cursor.execute("select * from consultora_pais ")
data = cursor.fetchall()
print("Connection established to: ",data)
conn.close()

conn = psycopg2.connect(
   database="d6dnjthjdhcjg2", 
   user='mhoadzckqtelgg', 
   password='d23acd0a4b499eb1ea118026c36297aa9e19dd60dfdee4c17d146341eebffdd2', 
   host='ec2-54-175-79-57.compute-1.amazonaws.com', 
   port= '5432'
)

cursor = conn.cursor()
cursor.execute("SELECT  consultora_postulante.nombre, apellido, consultora_idioma.nombre as Idioma, consultora_postulanteidioma.descripcion FROM consultora_postulanteidioma JOIN consultora_postulante ON postulante_id = consultora_postulante.id JOIN consultora_idioma ON idioma_id = consultora_idioma.id")
data = cursor.fetchall()
print("Connection established to: ",data)
conn.close()
